name: waste_to_go
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.5.2
  crypto: ^3.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  firebase_storage: ^11.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_svg: ^2.0.5
  freezed_annotation: ^2.2.0
  geocoding: ^2.1.0
  get_it: ^7.3.0
  go_router: ^6.5.8
  google_fonts: ^4.0.3
  google_maps_flutter: ^2.2.5
  image_picker: ^0.8.7+4
  intl: any
  json_annotation: ^4.8.0
  location: ^4.4.0
  ndialog: ^4.3.0
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/
